version: '4.16'

services:

  wordpress:
    image: wordpress
    restart: always
    ports:
      - 8080:80
    environment:
      WORDPRESS_DEBUG: 1 
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: "${DATABASE_USER}"
      WORDPRESS_DB_PASSWORD: "${DATABASE_PASSWORD}"
      WORDPRESS_DB_NAME: "${DATABASE_NAME}"
    volumes:
      - wordpress:/var/www/html
      - ./wp-content:/var/www/html/wp-content

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: "${DATABASE_NAME}"
      MYSQL_USER: "${DATABASE_USER}"
      MYSQL_PASSWORD: "${DATABASE_PASSWORD}"
      # MYSQL_RANDOM_ROOT_PASSWORD: '1'
      MYSQL_ROOT_PASSWORD: "${ROOT_PASSWORD}"
    volumes:
      - db:/var/lib/mysql

volumes:
  db:
  wordpress: